### ISSUE TITLE
Evaluate Creaper core integration details for server configuration

### ISSUE THREAD

**Issue by fabiobrz** [jboss-eap-qe/eap-microprofile-test-suite#35]
Purpose of this issue is to come to a decision over the better way - if any is needed - to integrate Creaper core into the TS to perform basic configuration tasks on the server model when running tests.

As it was discussed whether to adopt Creaper or a different tooling for server configuration previously, it should be defined also whether the chosen component should be _used_ as-is or wrapped somehow - i.e. simple integration facade (just with `enable` and `remove`) to provide easier migration to another tooling in case there should be any need to change chosen implementation.

**Comment by fabiobrz** [comment]
For sure it would be quite challenging to maintain a facade for such interaction in case the need for more complex server configuration requirements should show up so it's could be reasonable to use Creaper as it is with no wrapping at all, but that one should be a common decision so I created the issue.

**Comment by rsvoboda** [comment]
@mnovak1 needs to use server reloads, subsystem addition and maybe more. Can you please comment here about the way you plan to use Creaper ?

**Comment by fabiobrz** [comment]
Hi @rsvoboda, I need to use subsystem addition/removal and reload as well, I guess. 
What I thought is whether we should just go as-is, let's say with some kind of helper per spec module to perform those operation via Creaper and that's it.
This isn't a centralized approach which in turns have some pro (easy, quick, etc.) and cons (several points to maintain, approaches etc.), though, so I started the issue to see whether you all have any suggestion or idea.

**Comment by mnovak1** [comment]
@fabiobrz this is very good topic. Yes, there are definitely pros/cons. 

As @rsvoboda has mentioned at first I planned to use just a few simple commands like adding/removing extension/subsystem and reload. But thinking of it again I'll also use backup/restore config feature in Creaper and then in case we start to add real test scenarios (which is what we want) with databases, we'll most likely need to setup datasources. I also plan to test MP FT with graceful shutdown. I can imagine that @honza-kasik will need to adjust configuration of Elytron and Undertow for MP JWT. Based on above I'm afraid that we might end up with quite big facade. 

I agree that replacement of Creaper is a risk. However for WF/EAP we guarantee compatibility of Java API and CLI which implies there is low risk of breakage (it would be blocker for release) of Creaper.

Replacement of Creaper is possible but my opinion is that if anything goes wrong with Creaper it will be fixed in Creaper with maximum effort to keep Creaper API backward compatible. There are many test suites using it. Thus I'm more for using Creaper API directly but does not have strong opinion on this.

**Comment by fabiobrz** [comment]
Hi @mnovak1, yes I do agree on what you mention about the chance we could need more interaction as time goes by and with complex scenarios. 
I am scared by the facade too, not only because of the effort/cost needed to implement a further layer but also because of the nature of the component being wrapped, i.e. a management client.
So, following you in preferring direct usage of Creaper API.
Now the topic would be the best pattern - if any - to be used in order to implement those API calls in a centralized and easily maintainable way.

**Comment by honza-kasik** [comment]
@fabiobrz Thanks for bringing this out! This is  an important topic. Creaper already does all these things you are mentioning. AFAIK it is a facade to `org.jboss.as.controller.client.ModelControllerClient` and various other classes which have not so nice API (not so simple to use). Creaper introduces many nice patterns and basically it does things which we would do anyway. Until there are serious changes to `ModelControllerClient`, the server `API` or some serious changes in Java which will be non-backward compatible, everything will be working as-is. If there would be such changes we would have to adjust our non-Creaper tooling anyway. So in my opinion, there is no need to wrap Creaper to another layer. We don't want to re-invent wheel.

Creaper uses [`Command`s](https://github.com/wildfly-extras/creaper#building-commands) which provide a way how to reduce code redundancy and ease maintenance.

**Comment by fabiobrz** [comment]
@honza-kasik thanks. That's my point, too and I agree on the reasons you provided.
I am just trying out a very basic architecture to use it as-is, I'll let you know something during the afternoon.

**Comment by rsvoboda** [comment]
Do you think this discussion and explanations should translate into enhancements of https://github.com/wildfly-extras/creaper/blob/master/README.md ?

**Comment by mnovak1** [comment]
I've added `guildelines` flag. We'll need to document it in guildelines.

**Comment by mnovak1** [comment]
Closing. This will be documented as part of https://github.com/jboss-eap-qe/eap-microprofile-test-suite/issues/61.

Creaper Core API is used as it is, there is only helper provider class `ManagementClientProvider` for getting Creaper `OnlineManagementClient`.
